# This build will only build the image on any branch (besides main) where there is a push
name: Build Docker Image

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: false
          tags: earthlab/r-python-eds-lessons-env:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
