# ./environment.yml

name: base-python
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - pip
  
  
  
  # Core scientific python
  - numpy
  - pandas
  - tqdm  # Progress bar
  - kiwisolver
  
  # Plotting
  - matplotlib
  - plotly
  - seaborn
  
  # Machine Learning
  - scipy
  - scikit-learn
  
  # Deep Learning
  - pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch 
  - tensorflow
  - keras

  # Natural language processing
  - nltk
  - textblob
  


  # Game dev
  - pygame
  
  
  
  # Web dev
  - flask
  - django
  - djangorestframework
  
  
  
  # Jupyter Environment
  - papermill
  - autopep8
  - jupyterlab
  - notebook
  - ipython
  - jupyter_contrib_nbextensions
  - nbclean
  - nbresuse
  
  # Autograding
  - matplotcheck>=0.1.3
  - nbgrader